### ISSUE TITLE
dm-worker do not parse char escape as yaml standard

### ISSUE THREAD

**Issue by lastboy1228** [pingcap/dm#1317]
## Bug Report

1. I set the mydumper args to exclue the tables 'db_order_detail_00' to 'db_order_detail_99'
```
mydumpers:
  dump-db-prefix:
    skip-tz-utc: true
    extra-args: "--trx-consistency-only --regex '^db\\_(?!order\\_detail\\_)'"   
```

2. dm-work convert one backslash to two
```
["meeting some unsupported arguments"] [task=dm-task-mpay] [unit=dump] [argument="[--skip-tz-utc,--trx-consistency-only,--regex,\"'^db\\\\_(?!order\\\\_detail\\\\_)'\"]"]
```

The dm-worker just can't get the right regex, whatever I used to express backslash.
