### ISSUE TITLE
Configure clusters to optimize user experience for version 2.0.0GA or higher

### ISSUE THREAD

**Issue by aeoluswing** [pingcap/dm#1324]
## Question

Before asking a question, make sure you have:

- Searched existing Stack Overflow questions.
- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/pingcap/dm/issues?q=is%3Aissue)
- Read the documentation:
    - [Detailed documentation](https://pingcap.com/docs/tools/dm/overview/)
    - [简体中文文档](https://pingcap.com/docs-cn/tools/dm/overview/)

Is there any documentation on how to configure components such as grafana？For example,smtp configuration for grafana or alertmanager.I tried to modify the relevant configuration (`data/dm_monitor/deploy/grafana/grafana-3000/bin/conf/defaults.ini` or `data/dm_monitor/deploy/grafana/grafana-3000/conf/grafana.ini`),but it didn't work.The configuration is restored to the default value after executing the relevant command `tiup dm reload dm-cluster`.

Have I missed some documents on related topics？

**Comment by csuzhangxc** [comment]
see https://docs.pingcap.com/tidb-data-migration/stable/maintain-dm-using-tiup#update-configuration

**Comment by aeoluswing** [comment]
I found this document to update the configuration, but did not find a template related to the configuration file.[https://docs.pingcap.com/zh/tidb-data-migration/stable/maintain-dm-using-tiup](https://docs.pingcap.com/zh/tidb-data-migration/stable/maintain-dm-using-tiup)

**Comment by aeoluswing** [comment]
@csuzhangxc .thx for your response.Is there any template for edit config?

**Comment by csuzhangxc** [comment]
> @csuzhangxc .thx for your response.Is there any template for edit config?

search `配置文件模板` in https://docs.pingcap.com/zh/tidb-data-migration/stable/deploy-a-dm-cluster-using-tiup#%E7%AC%AC-2-%E6%AD%A5%E7%BC%96%E8%BE%91%E5%88%9D%E5%A7%8B%E5%8C%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by aeoluswing** [comment]
@csuzhangxc The problem that bothers me is mainly the parsing rules of the configuration field. I am not sure how to map from the file to the ini configuration.Below is my configuration snippet:
```
...
grafana_servers:
- host: 10.1.192.133
   ssh_port: 22
   port: 3000
   deploy_dir: /data/dm_monitor/deploy/grafana/grafana-3000
   arch: amd64
   os: linux
   config: smtp_enabled: true
   smtp_host: smtp.example.com:25
   smtp_user: test@example.com
   smtp_password: 123456
   smtp_skip_verify: false
   smtp_from_address: test.example.com
...
```

When I tried to save the configuration, I encountered the following error:
```
New topology could not be saved: Failed to parse topology file: yaml: unmarshal errors:
     line 74: field config not found in type spec.GrafanaSpec
```
