### ISSUE TITLE
Support converting unsupported collation to TiDB supported collation or skip the schema creation

### ISSUE THREAD

**Issue by namco1992** [pingcap/dm#1354]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB doesn't support `_unicode_ci`, however, this is a common collation that is widely used. Currently, DM can't handle the schemas with `_unicode_ci` as the schema creation will fail. The schema creation can't be bypassed, too.

**Describe the feature you'd like:**

1. DM should convert other unsupported collations to the supported collations (`_bin` and `_general_ci` if [new_collations_enabled_on_first_bootstrap](https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file#new_collations_enabled_on_first_bootstrap) is enabled);
2. If the auto conversion approach is not ideal, then at least allow the user to create schemas manually and then config the DM to skip the schema restore.

**Teachability, Documentation, Adoption, Migration Strategy:**

The auto-conversion or skip schema creation should be configured in the task configuration.

**Comment by lance6716** [comment]
Sounds great. currently DM will stop at that error so user can use [`handle-error`](https://docs.pingcap.com/tidb-data-migration/stable/handle-failed-sql-statements#handle-error) to replace that SQL, but an auto-conversion feature is definitely better.

Could you give an exmaple about how this configuration looks like in [task configuration](https://docs.pingcap.com/tidb-data-migration/stable/task-configuration-file-full)?

**Comment by namco1992** [comment]
> Sounds great. currently DM will stop at that error so user can use [`handle-error`](https://docs.pingcap.com/tidb-data-migration/stable/handle-failed-sql-statements#handle-error) to replace that SQL, but an auto-conversion feature is definitely better.

Hello @lance6716, from what I saw in the code and what I observed from my tests, `handle-error` can't be used during the dump and load, which means the error can't be handled when `task-mode: all`:
https://github.com/pingcap/dm/blob/1e9a0948a0a5bf8772b50cc58dd1ab8caebc90d8/dm/worker/subtask.go#L679-L683


> Could you give an exmaple about how this configuration looks like in [task configuration](https://docs.pingcap.com/tidb-data-migration/stable/task-configuration-file-full)?

I think the configuration could be under `Global setting` section:
```yaml
# ----------- Global setting -----------
## ********* Basic configuration *********
name: test                       # The name of the task. Should be globally unique.
task-mode: all                   # The task mode. Can be set to `full`/`incremental`/`all`.

# Other configurations here...

force-utf8-collation: general_ci # The collation to force convert to, only applicable to `utf8`/`utf8mb4` character sets. Available collations are `bin`/`general_ci`(only if `new_collations_enabled_on_first_bootstrap` is enabled)
skip-schema-restoration: true    # Weather to skip the schema restoration. It only takes effect in `all` task mode
```

I feel it's good to have the option to allow users to skip the schema restoration, which enables users to have full control of the schema creation if needed.
WDYT?
