### ISSUE TITLE
dmctl fail to operate-source when flavor is not specified and GTID is set

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dm#1380]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

cat source.yaml

```
source-id: "test"

enable-gtid: true
enable-relay: true
relay-binlog-gtid: "8fed3d32-1e6e-11eb-9e0f-0242ac110003:1-2933"
from:
  host: "127.0.0.1"
  user: "root"
  password: ""
  port: 3306
purge:
  remain-space: 15
```

./dmctl operator-source create source.yaml

2. What did you expect to see?
Add source successfully.

3. What did you see instead?
```
[code=11009:class=dm-worker:scope=internal:level=high], Message: relay-binlog-gtid 8fed3d32-1e6e-11eb-9e0f-0242ac110003:1-2933: parse GTID 8fed3d32-1e6e-11eb-9e0f-0242ac110003:1-2933, RawCause: invalid flavor 
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
       `1fc1f5fcd7b25d0bfd05589a053ccfe1c4f59422`
