### ISSUE TITLE
block-allow-list and other configurations can't work when set uppercase db/table name and `case-sensitive = true`

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1676]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

set task configurations like

```yaml
...
case-sensitive: true
...

black-white-list:
  global:
    do-dbs: ["do_db"]
    do-tables:
    - db-name: "do_db"
      tbl-name: "DO_TABLE"
```

2. What did you expect to see?

table `do_db`.`DO_TABLE` is synced

3. What did you see instead?

table `do_db`.`DO_TABLE` is not synced

4. workaround:

try set `case-sensitive: false`
