### ISSUE TITLE
malformed task configuration file may cause DM-worker panic

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1803]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```yaml
---
# ----------- Global setting -----------
## ********* Basic configuration *********
name: sql-manager-migration
task-mode: all
is-sharding: false
case-sensitive: true
target-database:
  host: "127.0.0.1"
  port: 4000
  user: "root"
  password: ""
# ----------- Instance configuration -----------
mysql-instances:
  -
    source-id: "mysql-replica-01"
    block-allow-list: "list-manager"
    loader-config-name: "loader-manager"
    mydumper-config-name: "mydumper-manager"
    syncer-config-name: "syncer-manager"
block-allow-list:
  list-manager:
    do-tables:
      - db-name: "manager"
loaders:
  loader-manager:
    dir: "/var/lib/dm-worker/manager"
mydumpers:
  mydumper-manager:
    threads: 4
    chunk-filesize: 64
syncers:
  syncer-manager:
    worker-count: 4
    batch: 5
    safe-mode: true
ignore-checking-items: ["all"]
```

2. What did you expect to see?

DM reports proper error message 

3. What did you see instead?

DM-worker panicked. And if the worker didn't restart by other process (for example, systemctl), after keepalive TTL, DM-master will schedule the task to a new worker, which causes panic again.

4. Cause

from above configuration file, we could see there's no `tbl-name`

```yaml
    do-tables:
      - db-name: "manager"
```

and dumpling will return an error in `constructArgs `
https://github.com/pingcap/dm/blob/d103118d5cf074e34d8b7246f49cf3211f263ca1/dumpling/dumpling.go#L61-L65

now we didn't check `err` and return immediately, so following lines will access `nil` `m.dumpConfig`

**Comment by coderplay** [comment]
As described above, a simple invalid configuration item would turn down all the DM workers. 

Detailed steps to reproduce: 

1. Assuming that we have created a data source named `mysql-source`, and create a `migration.yaml` with below content
  ```yaml
  ---
  # ----------- Global setting -----------
  ## ********* Basic configuration *********
  name: sql-manager-migration
  task-mode: all
  is-sharding: false
  case-sensitive: true
  target-database:
    host: "127.0.0.1"
    port: 4000
    user: "root"
    password: ""
  # ----------- Instance configuration -----------
  mysql-instances:
    -
      source-id: "mysql-source"
      block-allow-list: "list-manager"
      loader-config-name: "loader-manager"
      mydumper-config-name: "mydumper-manager"
      syncer-config-name: "syncer-manager"
  block-allow-list:
    list-manager:
      do-tables:
        - db-name: "manager"
  loaders:
    loader-manager:
      dir: "/var/lib/dm-worker/manager"
  mydumpers:
    mydumper-manager:
      threads: 4
      chunk-filesize: 64
  syncers:
    syncer-manager:
      worker-count: 4
      batch: 5
      safe-mode: true
  
  ignore-checking-items: ["all"]
  ```
2. Submit the task through command `dmctl`, then we will get below response that indicates a successful submission
  ```
  $ /dmctl --master-addr tidb-dm-master-0:8261 start-task migration.yaml
  {
      "result": true,
      "msg": "",
      "sources": [
          {
              "result": true,
              "msg": "",
              "source": "mysql-source",
              "worker": "tidb-dm-worker-1"
          }
      ]
  }
  ```
3. However if we query the task status, the task is failed with a *confusing* error message.
  ```
   /dmctl --master-addr tidb-dm-master-0:8261 query-status sql-manager-migration
  {
      "result": true,
      "msg": "",
      "sources": [
          {
              "result": false,
              "msg": "[code=38008:class=dm-master:scope=internal:level=high], Message: grpc request error, RawCause: rpc error: code = Unavailable desc =
  connection error: desc = \"transport: Error while dialing dial tcp 10.240.0.80:8262: connect: connection refused\"",
              "sourceStatus": {
                  "source": "mysql-source",
                  "worker": "",
                  "result": null,
                  "relayStatus": null
              },
              "subTaskStatus": [
              ]
          }
      ]
  ```
4. Look into the logs of assigned worker, we notice the worker is crashed. 

  ```
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x1df8926]
  
  goroutine 332 [running]:
  github.com/pingcap/dm/dumpling.(*Dumpling).detectSQLMode(0xc0008cc720, 0x334ade0, 0xc0008d5f20)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dumpling/dumpling.go:297 +0x346
    github.com/pingcap/dm/dumpling.(*Dumpling).Init(0xc0008cc720, 0x334ade0, 0xc0008d5f20, 0x334ade0, 0xc0008d5f20)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dumpling/dumpling.go:62 +0x97
    github.com/pingcap/dm/dm/worker.(*SubTask).Init(0xc0002feb40, 0x0, 0x0)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/subtask.go:150 +0x1dc
    github.com/pingcap/dm/dm/worker.(*SubTask).Run(0xc0002feb40, 0x2)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/subtask.go:193 +0x20b
    github.com/pingcap/dm/dm/worker.(*Worker).StartSubTask(0xc0008fee00, 0xc0008b5180, 0x2, 0x0, 0x0)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/worker.go:419 +0x3e0
    github.com/pingcap/dm/dm/worker.(*Worker).EnableHandleSubtasks(0xc0008fee00, 0x0, 0x0)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/worker.go:328 +0x799
    github.com/pingcap/dm/dm/worker.(*Server).enableHandleSubtasks(0xc000130480, 0xc000928c60, 0xc00089d201, 0x0, 0x0)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/server.go:670 +0x130
    github.com/pingcap/dm/dm/worker.(*Server).operateSourceBound(0xc000130480, 0xc00093c4d0, 0x8, 0xc00093c4e0, 0x10, 0x0, 0x76, 0x0, 0xc0002e6b00)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/server.go:656 +0x257
    github.com/pingcap/dm/dm/worker.(*Server).handleSourceBound(0xc000130480, 0x334ad60, 0xc000926080, 0xc000500060, 0xc0005000c0, 0x334ad60, 0xc000926080)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/server.go:580 +0x433
    github.com/pingcap/dm/dm/worker.(*Server).observeSourceBound(0xc000130480, 0x334ad60, 0xc0000c8580, 0x72, 0x0, 0x0)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/server.go:405 +0xd41
    github.com/pingcap/dm/dm/worker.(*Server).Start.func4(0xc000130480, 0x72, 0x334ad60, 0xc0000c8580)
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/server.go:169 +0x9c
    created by github.com/pingcap/dm/dm/worker.(*Server).Start
            /home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.2/go/src/github.com/pingcap/dm/dm/worker/server.go:166 +0x773
    
  
  ```
 % kubectl get pod -n tidb
NAME                                 READY   STATUS             RESTARTS   AGE
tidb-discovery-678c5d87-8gdlr        1/1     Running            0          4d14h
tidb-dm-discovery-77bfd69b59-tdrwg   1/1     Running            0          4d14h
tidb-dm-master-0                     1/1     Running            0          12m
tidb-dm-worker-0                     1/1     CrashLoopBackOff   6          11m
tidb-dm-worker-1                     0/1     CrashLoopBackOff   6          12m
```




Dumpling.init() should check ersr before moving to the next step
Dumpling should log the err 
DM master shouldn’t accept a malformatted task configuration
If a task is constantly facing errors, it shouldn’t be passed to other workers. Otherwise it would spread the errors to all workers, therefore causing all workers in crash loops.
Tidb-operator should NOT scale out when workers are in crash loops, otherwise it will create too many workers.
DM configurations are not well documented
