### ISSUE TITLE
how can i config dumpling in dm？

### ISSUE THREAD

**Issue by lddlww** [pingcap/dm#877]
```
mydumpers:                       
  global:                            
    mydumper-path: "./bin/mydumper"  
    threads: 4                      
    chunk-filesize: 64             
    skip-tz-utc: true              
    extra-args: "--no-locks" 
```

how can i config dumpling replace mydumpers?

**Comment by csuzhangxc** [comment]
just config them in `mydumpers` section.

**Comment by lddlww** [comment]
ok，thanks

**Comment by lddlww** [comment]
download dm2.0-beta，i can't find dumpling cmd：
```
[ 15:09:40-root@7bf7ngdq:bin ]#ll
total 294716
-rwxr-xr-x 1 root root 63551837 Jun 19 10:45 dmctl
-rwxr-xr-x 1 root root 74355176 Jun 19 10:45 dm-master
-rwxr-xr-x 1 root root 64055293 Jun 19 10:45 dm-portal
-rwxr-xr-x 1 root root 87026084 Jun 19 10:45 dm-worker
-rwxr-xr-x 1 root root 12788472 Jun 19 10:45 mydumper
```

do i need to download ```dumpling``` separately？

**Comment by lance6716** [comment]
> download dm2.0-beta，i can't find dumpling cmd：
> 
> ```
> [ 15:09:40-root@7bf7ngdq:bin ]#ll
> total 294716
> -rwxr-xr-x 1 root root 63551837 Jun 19 10:45 dmctl
> -rwxr-xr-x 1 root root 74355176 Jun 19 10:45 dm-master
> -rwxr-xr-x 1 root root 64055293 Jun 19 10:45 dm-portal
> -rwxr-xr-x 1 root root 87026084 Jun 19 10:45 dm-worker
> -rwxr-xr-x 1 root root 12788472 Jun 19 10:45 mydumper
> ```
> 
> do i need to download `dumpling` separately？

You could find here https://github.com/pingcap/dumpling and use it in **DM 1.0**. For DM 2.0, dumpling is embedded and reuse `mydumper` as configuration name.

**Comment by lddlww** [comment]
```
mydumpers:                       
  global:                            
    mydumper-path: "./bin/mydumper"  
    threads: 4                      
    chunk-filesize: 64             
    skip-tz-utc: true            
```

but how can i config ```mydumper-path``` in dm 2.0 or  replace it null?

**Comment by lance6716** [comment]
> ```
> mydumpers:                       
>   global:                            
>     mydumper-path: "./bin/mydumper"  
>     threads: 4                      
>     chunk-filesize: 64             
>     skip-tz-utc: true            
> ```
> 
> but how can i config `mydumper-path` in dm 2.0 or replace it null?

https://docs.pingcap.com/zh/tidb-data-migration/dev/task-configuration-file-full in DM 2.0 just delete this line

**Comment by lddlww** [comment]
thank you very much

**Comment by lddlww** [comment]
in mysql db,i have three tables，like:
```
db1.t1
db1.t2
db1.t3
```

at first，in task.yaml，mydumper config like:
```
mydumpers:                       
  global:                             
    threads: 4                      
    chunk-filesize: 64             
    skip-tz-utc: true  
    extra-args: "-B db1 -T db1.t1 -T db1.t2 "
```

then start-task task.yaml；after a while，i want to dump db1.t3，how can i do？，follow config is not effect：
```
mydumpers:                       
  global:                             
    threads: 4                      
    chunk-filesize: 64             
    skip-tz-utc: true  
    extra-args: "-B db1 -T db1.t1 -T db1.t2  -T db1.t3"
```

**Comment by lance6716** [comment]
> dm version:
> 
> ```
> Release Version: v2.0.0-beta.2
> Git Commit Hash: e1c5376b4d3d31c353c6431d3eb9e91dc0608105
> Git Branch: master
> UTC Build Time: 2020-06-19 02:26:16
> Go Version: go version go1.13 linux/amd64
> ```
> 
> in mysql db,i have three tables，like:
> 
> ```
> db1.t1
> db1.t2
> db1.t3
> ```
> 
> at first，in task.yaml，mydumper config like:
> 
> ```
> mydumpers:                       
>   global:                             
>     threads: 4                      
>     chunk-filesize: 64             
>     skip-tz-utc: true  
>     extra-args: "-B db1 -T db1.t1 -T db1.t2 "
> ```
> 
> then start-task task.yaml；after a while，i want to dump db1.t3，how can i do？，follow config is not effect：
> 
> ```
> mydumpers:                       
>   global:                             
>     threads: 4                      
>     chunk-filesize: 64             
>     skip-tz-utc: true  
>     extra-args: "-B db1 -T db1.t1 -T db1.t2  -T db1.t3"
> ```

Should stop task then change config file. You could turn to https://asktug.com/ to get community's help

**Comment by lddlww** [comment]
ok，thanks for reply

**Comment by lddlww** [comment]
when i just want to dump db1.t2 and db1.t3，mydumper config like follow：
```
mydumpers:                       
  global:                             
    threads: 4                      
    chunk-filesize: 64             
    skip-tz-utc: true  
    extra-args: "-B db1 -T db1.t1 -T db1.t2  -T db1.t3"
```

but i found dumplings dump all tables always（i don't want to config ```black-white-list```）
